### PR TITLE
Introduce Parse() 

### PR DESCRIPTION
**Pull request by oflebbe**
Introduce Parse() with Reader Interface, rewrite ParseFile and ParseBytes to use it.

Reason is I would like to use the library with Reader Interface so I do not have to load the complete GPX file for parsing. I can stream it not from an HTTP connection for instance, or parse a compressed GPX file without unpacking first.

### CODE REVIEW

**Comment by tkrajina** [comment]
Makes sense, add a test and I'm merging it!

**Comment by oflebbe** [comment]
I considered to write a test. Since ParseFile() and ParseBytes() are now using the Parse() functionality I am asking myself what kind of Test would bring additional value. A Test opening a test file and submitting to Parse() would essentially identical to the ParseFile() implementation, which is already been tested. 
Seems like I have to be more creative :)

**Comment by oflebbe** [comment]
Adding a test demonstrating reading from a compressed source . Maybe this should have been an Example Test, but anyway.

**Comment by tkrajina** [comment]
Ah, right, thanks for the pull request!

**Comment by jlelse** [comment]
@oflebbe Maybe it's a stupid question, but I'm trying to understand: Why didn't you use `strings.NewReader` and `bytes.NewReader` for the string and bytes methods?

**Comment by oflebbe** [comment]
@jlelse Maybe my mind was in weekend mode . Will issue a PR to fix. Thanks for asking 👍

**Pull request merged**
